CustomersManagementSystem/Models/Invoice.cs
namespace CustomersManagementSystem.Models;

public class Invoice
{
   
    
    public Guid Id { get; set; }

    public string Description { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
   
    public decimal Discount { get; set; }
    public decimal Total { get; set; }
    public decimal GrandTotal { get; set; }

    [Required]
    public DateTime InvoiceDate { get; set; }

    public bool IsPaid { get; set; }

    public Guid CustomerId { get; set; }
    public Customer Customer { get; set; }
}

CustomersManagementSystem/ViewModels/Invoices/InvoiceCreationViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CustomersManagementSystem.ViewModels.Invoices;

public class InvoiceCreationViewModel
{
    public string Description { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    [Range(0, 100)]
    public decimal Discount { get; set; }
    [DisplayName("Customer Name")]
    public Guid CustomerId { get; set; }

    [Display(Name = "Already Paid")]
    public bool IsPaid { get; set; }
  
}

CustomersManagementSystem/ViewModels/Invoices/InvoiceViewModel.cs
namespace CustomersManagementSystem.ViewModels.Invoices;

public class InvoiceViewModel
{
    public Guid Id { get; set; }
    public string Description { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
    [Display(Name = "Customer Name")]
    public Guid CustomerId { get; set; }

    [Display(Name = "Customer Name")]
    public string CustomerName { get; set; }
    public decimal Discount { get; set; }
    [Display(Name = "Total")]
    public decimal Total { get; set; }

    [Display(Name = "Grand Total")]
    public decimal GrandTotal { get; set; }

    [Display(Name = "Already Paid")]
    public bool IsPaid { get; set; }

    [Display(Name = "Invoice Date")]
    public DateTime InvoiceDate { get; set; }
}

CustomersManagementSystem/Controllers/InvoiceController.cs
namespace CustomersManagementSystem.Controllers;

public class InvoiceController : Controller
{
    #region Constructor
    private readonly ApplicationDbContext _context;
    private readonly IInvoiceRepository _invoiceRepository;
    private readonly IMapper _mapper;
    public InvoiceController(ApplicationDbContext context,
        IInvoiceRepository invoiceRepository,
        IMapper mapper)
    {
        _context = context;
        _invoiceRepository = invoiceRepository;
        _mapper = mapper;
    }
    #endregion

    // GET: Invoice
    public async Task<IActionResult> Index()
    {
        var invoices = await _invoiceRepository.GetAsync();
        var invoicesToReturn = _mapper.Map<IEnumerable<InvoiceViewModel>>(invoices);
        return View(invoicesToReturn);
    }

    // GET: Invoice/Details/5
    public async Task<IActionResult> Details(Guid id)
    {
        if (await _invoiceRepository.IsExistAsync(id) 
            || await _invoiceRepository.GetAsync() == null)
            return NotFound();
        
        var invoice = await _invoiceRepository.GetAsync(id);
        if (invoice == null)
        {
            return NotFound();
        }

        return View(invoice);
        
    }

    // GET: Invoice/Create
    public IActionResult Create()
    {
        ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name");
        return View();
    }

    // POST: Invoice/Create

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Description,Quantity,Price,CustomerId,Discount,IsPaid")] InvoiceCreationViewModel invoice)
    {
        if (ModelState.IsValid)
        {
           var invoiceToAdd = _mapper.Map<Invoice>(invoice);
            invoiceToAdd.InvoiceDate = DateTime.UtcNow;
            invoiceToAdd.Total = invoiceToAdd.Quantity * invoiceToAdd.Price;
            invoiceToAdd.GrandTotal = invoiceToAdd.Total - ((invoiceToAdd.Total * invoiceToAdd.Discount) / 100);
            _invoiceRepository.Add(invoiceToAdd);
            
            await _invoiceRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }
        ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name", invoice.CustomerId);
        return View(invoice);
    }

    // GET: Invoice/Edit/5
    public async Task<IActionResult> Edit(Guid? id)
    {
        if (id == null || _context.Invoices == null)
        {
            return NotFound();
        }

        var invoice = await _context.Invoices.FindAsync(id);
        if (invoice == null)
        {
            return NotFound();
        }
        ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name", invoice.CustomerId);
        return View(invoice);
    }
   
    // GET: Invoice/Delete/5

    public async Task<IActionResult> Delete(Guid? id)
    {
        if (id == null || _context.Invoices == null)
        {
            return NotFound();
        }

        var invoice = await _context.Invoices
            .Include(i => i.Customer)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (invoice == null)
        {
            return NotFound();
        }

        return View(invoice);
    }

    // POST: Invoice/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        if (_context.Invoices == null)
        {
            return Problem("Entity set 'ApplicationDbContext.Invoices'  is null.");
        }
        var invoice = await _context.Invoices.FindAsync(id);
        if (invoice != null)
        {
            _context.Invoices.Remove(invoice);
        }
        
        await _context.SaveChangesAsync();
        return RedirectToAction("index");
    }
  
    public async Task<IActionResult> AddOrEdit(Guid? id)
    {
        if (id == null)
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name");
            return View(new InvoiceViewModel());
        }
        else
        {
            //var invoiceFromDb = await _invoiceRepository.IsExistAsync(id);
            var invoiceFromDb = await _context.Invoices.FindAsync(id);
            
            if (invoiceFromDb == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Name");
            var invoiceViewModel = _mapper.Map<InvoiceViewModel>(invoiceFromDb);
            return View(invoiceViewModel);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddOrEdit(Guid id, [Bind("Description,Quantity,Price,CustomerId,Discount")]
    InvoiceCreationViewModel invoiceViewModel)
    {
        if (ModelState.IsValid)
        {
            //Insert
            if (id == Guid.Empty)
            {
                var invoiceToAdd = _mapper.Map<Invoice>(invoiceViewModel);
                invoiceToAdd.InvoiceDate = DateTime.UtcNow;
                invoiceToAdd.Total = invoiceToAdd.Quantity * invoiceToAdd.Price;
                invoiceToAdd.GrandTotal = invoiceToAdd.Total - ((invoiceToAdd.Total * invoiceToAdd.Discount) / 100);
                _invoiceRepository.Add(invoiceToAdd);

                await _invoiceRepository.SaveAsync();
            }
            //Update
            else
            {
                try
                {
                    var invoiceToEdit = _mapper.Map<Invoice>(invoiceViewModel);
                    invoiceToEdit.Id = id;
                    invoiceToEdit.Total = invoiceToEdit.Quantity * invoiceToEdit.Price;
                    invoiceToEdit.GrandTotal = invoiceToEdit.Total - ((invoiceToEdit.Total * invoiceToEdit.Discount) / 100);
                    _invoiceRepository.Update(invoiceToEdit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                   /* if (!TransactionModelExists(invoiceViewModel.TransactionId))
                    { return NotFound(); }
                    else
                    { throw; }*/ 
                }
            }
            //var invoices = await _invoiceRepository.GetAsync();

            //var invoicesToReturn = _mapper.Map<IEnumerable<InvoiceViewModel>>(invoices);

            return RedirectToAction("index");
        }
        return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", invoiceViewModel) });
    }
}

CustomersManagementSystem/Views/Invoice/AddOrEdit.cshtml
@model CustomersManagementSystem.ViewModels.Invoices.InvoiceViewModel

@{
    Layout = null;
}

<h4>Invoice</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger" autocomplete="off"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Quantity" class="control-label"></label>
                        <input asp-for="Quantity" class="form-control" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Discount" class="control-label"></label>
                        <input asp-for="Discount" class="form-control" />
                        <span asp-validation-for="Discount" class="text-danger"></span>
                    </div>
                </div>
               
            </div>
           
           <br />
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomersManagementSystem/Views/Invoice/Delete.cshtml
@model CustomersManagementSystem.Models.Invoice

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

CustomersManagementSystem/Views/Invoice/Details.cshtml
@model CustomersManagementSystem.Models.Invoice

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CustomersManagementSystem/Views/Invoice/Index.cshtml
@model IEnumerable<CustomersManagementSystem.ViewModels.Invoices.InvoiceViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Invoices</h1>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll",Model)
</div>
 

CustomersManagementSystem/Views/Invoice/_ViewAll.cshtml
@model IEnumerable<CustomersManagementSystem.ViewModels.Invoices.InvoiceViewModel>

<div>
    <table class="table table-responsive" id="view-all">
        <thead class="thead-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Discount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GrandTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsPaid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceDate)
            </th>
            <th>
                <p>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit","Invoice",null,Context.Request.Scheme )','New Invoice')"
                    class="btn btn-success text-white btn-sm">
                    <i class="fas fa-random"></i> New Invoice</a>
                </p>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="row_@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Discount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GrandTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsPaid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InvoiceDate)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit","Invoice",
                        new {id=item.Id},Context.Request.Scheme )',
                        'Edit Invoice')" class="btn btn-sm btn-warning">
                        Edit
                    </a>
            
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Details</a> |
                        
                    <form asp-action="Delete" asp-route-id="@item.Id"
                    onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                        <input type="hidden" asp-for="@item.Id" />
                        <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
    </table>
</div>